package com.techbec.springmvc.model;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Feed41 generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "feed_41", catalog = "emoncms")
public class FeedData implements java.io.Serializable {

    private FeedDataId id;

    public FeedData() {
    }

    public FeedData(FeedDataId id) {
        this.id = id;
    }

    @EmbeddedId

    @AttributeOverrides({ @AttributeOverride(name = "time", column = @Column(name = "time")),
            @AttributeOverride(name = "data", column = @Column(name = "data", precision = 12, scale = 0)) })
    public FeedDataId getId() {
        return this.id;
    }

    public void setId(FeedDataId id) {
        this.id = id;
    }

}
