package com.techbec.springmvc.model;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Feed41Id generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class FeedDataId implements java.io.Serializable {

    private Integer time;
    private Float   data;

    public FeedDataId() {
    }

    public FeedDataId(Integer time, Float data) {
        this.time = time;
        this.data = data;
    }

    @Column(name = "time")
    public Integer getTime() {
        return this.time;
    }

    public void setTime(Integer time) {
        this.time = time;
    }

    @Column(name = "data", precision = 12, scale = 0)
    public Float getData() {
        return this.data;
    }

    public void setData(Float data) {
        this.data = data;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof FeedDataId))
            return false;
        FeedDataId castOther = (FeedDataId) other;

        return ((this.getTime() == castOther.getTime()) || (this.getTime() != null && castOther.getTime() != null
                && this.getTime().equals(castOther.getTime())))
                && ((this.getData() == castOther.getData()) || (this.getData() != null && castOther.getData() != null
                        && this.getData().equals(castOther.getData())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getTime() == null ? 0 : this.getTime().hashCode());
        result = 37 * result + (getData() == null ? 0 : this.getData().hashCode());
        return result;
    }

}
