package com.techbec.springmvc.model;
// Generated 10-May-2017 11:25:15 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Input generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "input", catalog = "emoncms")
public class Input implements java.io.Serializable {

    private Integer id;
    private Integer userid;
    private String  name;
    private String  description;
    private String  nodeid;
    private String  processList;
    private Integer time;
    private Float   value;

    public Input() {
    }

    public Input(Integer userid, String name, String description, String nodeid, String processList, Integer time,
            Float value) {
        this.userid = userid;
        this.name = name;
        this.description = description;
        this.nodeid = nodeid;
        this.processList = processList;
        this.time = time;
        this.value = value;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "userid")
    public Integer getUserid() {
        return this.userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    @Column(name = "name", length = 65535)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "description", length = 65535)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "nodeid", length = 65535)
    public String getNodeid() {
        return this.nodeid;
    }

    public void setNodeid(String nodeid) {
        this.nodeid = nodeid;
    }

    @Column(name = "processList", length = 65535)
    public String getProcessList() {
        return this.processList;
    }

    public void setProcessList(String processList) {
        this.processList = processList;
    }

    @Column(name = "time")
    public Integer getTime() {
        return this.time;
    }

    public void setTime(Integer time) {
        this.time = time;
    }

    @Column(name = "value", precision = 12, scale = 0)
    public Float getValue() {
        return this.value;
    }

    public void setValue(Float value) {
        this.value = value;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof Input))
            return false;
        Input other = (Input) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;

        return true;
    }

    @Override
    public String toString() {
        return "Input [userid=" + userid + ", name=" + name + ", description=" + description
                + ", nodeid=" + nodeid + ", processList=" + processList
                + ", time=" + time + ", value=" + value + "]";
    }
}
